
server:
  port: 10601

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dawnchat?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: DawnGhost
    password: homeworld
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: f5ac3ad838bfbd7ca1a1022ad10fe4ee
            client-secret: zrv06WuszXIy3zVtbJj7nKodcUJx5mio
            scope: profile_nickname, account_email, profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:10601/login/oauth2/code/kakao
            client-authentication-method: POST
        provider:
           kakao:
             authorization-uri: https://kauth.kakao.com/oauth/authorize
             token-uri: https://kauth.kakao.com/oauth/token
             user-info-uri: https://kapi.kakao.com/v2/user/me
             user-name-attribute: id



#custom:
#  oauth2:
#    kakao:
#      client-id: kakao-client-id

#http://localhost:10601/login/oauth2/code/kakao

